Repository crossplane/crossplane-runtime, pull requests merged in 2020-09, with the labels that each got.

#192 Update with desired object in APIUpdatingApplicator
  pkg/resource/api.go
  pkg/resource/api_test.go
Labels: release/behaviour-change

#195 Add TypedReferenceTo meta utility
  pkg/meta/meta.go
  pkg/meta/meta_test.go
  pkg/reference/reference_test.go
  pkg/resource/resource.go
Labels: release/breaking-api-change

#196 Remove unused conditions, and make the rest CamelCase
  apis/core/v1alpha1/condition.go
  pkg/reconciler/target/reconciler.go
  pkg/reconciler/target/reconciler_test.go
Labels: release/breaking-api-change

#197 Mark Claim and KubeApp reconcilers deprecated.
  pkg/reconciler/claimbinding/doc.go
  pkg/reconciler/claimdefaulting/doc.go
  pkg/reconciler/claimscheduling/doc.go
  pkg/reconciler/target/doc.go
Labels: release/api-deprecation

#200 Indicate whether Apply errors are due to a resource being uncontrollable
  pkg/resource/resource.go
  pkg/resource/resource_test.go
Labels: release/backwards-compatible

#201 Remove support for resource claims and classes
  apis/core/v1alpha1/bindingphase.go
  apis/core/v1alpha1/policies.go
  apis/core/v1alpha1/resource.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/claimbinding/api.go
  pkg/reconciler/claimbinding/api_test.go
  pkg/reconciler/claimbinding/configurator.go
  pkg/reconciler/claimbinding/configurator_test.go
  pkg/reconciler/claimbinding/doc.go
  pkg/reconciler/claimbinding/reconciler.go
  pkg/reconciler/claimbinding/reconciler_test.go
  pkg/reconciler/claimdefaulting/doc.go
  pkg/reconciler/claimdefaulting/reconciler.go
  pkg/reconciler/claimdefaulting/reconciler_test.go
  pkg/reconciler/claimscheduling/doc.go
  pkg/reconciler/claimscheduling/reconciler.go
  pkg/reconciler/claimscheduling/reconciler_test.go
  pkg/reconciler/managed/reconciler.go
  pkg/reconciler/managed/reconciler_test.go
  pkg/reconciler/secret/reconciler_test.go
  pkg/reconciler/target/reconciler.go
  pkg/reconciler/target/reconciler_test.go
  pkg/resource/api_test.go
  pkg/resource/enqueue_handlers.go
  pkg/resource/enqueue_handlers_test.go
  pkg/resource/fake/mocks.go
  pkg/resource/interfaces.go
  pkg/resource/predicates.go
  pkg/resource/predicates_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
Labels: release/breaking-api-change, release/very-breaking-api-change
